wip: ci (debugging)

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -23,7 +23,7 @@ jobs:
       COMMIT: ${{ github.sha }}
       REPO: user
       GO_VERSION: 1.7.5
-      GOPATH: /home/runner/work/user/user/go
+      GOPATH: /home/runner/go
 
     steps:
       - uses: actions/checkout@v4
@@ -40,38 +40,54 @@ jobs:
 
       - name: Install dependencies
         run: make deps 
-
-      - name: Install/Downgrade MongoDB to version 3.6
+    
+      - name: Check if Glide is installed
         run: |
-          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
-          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
-          wget -qO - https://pgp.mongodb.com/server-3.6.asc | sudo tee /etc/apt/trusted.gpg.d/mongodb-org-3.6.gpg
-          echo "deb [trusted=yes arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
-          sudo apt-get update
-          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"
-
-      - name: Check if port 8084 is in use and stop the process
-        run: |
-          if sudo lsof -i :8084; then
-            echo "Port 8084 is in use. Stopping the process..."
-            sudo fuser -k 8084/tcp
+          if command -v glide &> /dev/null; then
+            echo "Glide is installed"
+            glide --version
           else
-            echo "Port 8084 is free."
+            echo "Glide is not installed"
+            exit 1
           fi
-          
-      - name: Unit Tests
-        run: glide novendor| xargs go test -v
 
-      - name: Run Docker Test
-        run: make dockertest
-
-      - name: Automatic Tagging of Releases
-        id: increment-git-tag
+      - name: Debug workspace
         run: |
-          chmod +x scripts/git_update_tag.sh
-          bash scripts/git_update_tag.sh -v patch
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          echo "GOPATH: $GOPATH"
+          echo "Current directory: $(pwd)"
+          ls go/src/github.com/exam-rncp/user
+
+      # - name: Install/Downgrade MongoDB to version 3.6
+      #   run: |
+      #     wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+      #     sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+      #     wget -qO - https://pgp.mongodb.com/server-3.6.asc | sudo tee /etc/apt/trusted.gpg.d/mongodb-org-3.6.gpg
+      #     echo "deb [trusted=yes arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
+      #     sudo apt-get update
+      #     sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"
+
+      # - name: Check if port 8084 is in use and stop the process
+      #   run: |
+      #     if sudo lsof -i :8084; then
+      #       echo "Port 8084 is in use. Stopping the process..."
+      #       sudo fuser -k 8084/tcp
+      #     else
+      #       echo "Port 8084 is free."
+      #     fi
+          
+      # - name: Unit Tests
+      #   run: glide novendor| xargs go test -v
+
+      # - name: Run Docker Test
+      #   run: make dockertest
+
+      # - name: Automatic Tagging of Releases
+      #   id: increment-git-tag
+      #   run: |
+      #     chmod +x scripts/git_update_tag.sh
+      #     bash scripts/git_update_tag.sh -v patch
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       # - name: Docker build and push
       #   env:
